Move MSBuildLocator initialization into a module initializer
Integration tests were failing with this error:

```
System.TypeInitializationException: The type initializer for 'Incrementalist.Cmd.StaticGraphBuildEngine' threw an exception.
---> System.InvalidOperationException: Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
    Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
    This dependency arises from when a method is just-in-time compiled, so it breaks even if the reference to a Microsoft.Build type has not been executed.
```