Use Static Graph to improve performance of solutions and projects parsing (#424)
* Add multiple target frameworks to ProjectA and ProjectB

This demonstrates that project dependency detection has a bug and makes ShouldDetectProjectChanges fail.

* Fix missing project dependency detection

When multiple target frameworks are defined, the dictionary of source file to project must keep all the project ids. Choosing just one with `.First()` can lead to failure because the project id might correspond to a target framework that does not match the target framework of the referencing project.

* Abstract away Microsoft.CodeAnalysis from the core Incrementalist project

* Implement faster build engine with the Static Graph feature of Microsoft.Build

* Implement logging for the static graph build engine

* Move MSBuildLocator initialization into a module initializer

Integration tests were failing with this error:

```
System.TypeInitializationException: The type initializer for 'Incrementalist.Cmd.StaticGraphBuildEngine' threw an exception.
---> System.InvalidOperationException: Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
    Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
    This dependency arises from when a method is just-in-time compiled, so it breaks even if the reference to a Microsoft.Build type has not been executed.
```

* Fix integration tests

* Refine the BuildEngine API

* Simplify BuildAnalysisResultTests

* Avoid some unnecessary allocations

* Properly dispose the BuildEngine instance

* Add an --engine option to switch between the StaticGraph and Workspace engines

* Add a -BuildEngine parameter to the integration tests

* Tr to diagnose Azure pipeline failure

MSBuild chokes when evaluating https://github.com/dotnet/msbuild/blob/695b1ef88c242c19a95c9f6a504a2376661762c2/src/Tasks/Microsoft.Common.CurrentVersion.targets#L93 when constructing the `ProjectGraph` instance.

> 2025-05-08T19:43:44.0720454Z [xUnit.net 00:00:52.48]       ---- Microsoft.Build.Exceptions.InvalidProjectFileException : The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 7.0)" cannot be evaluated. The type initializer for 'Microsoft.Build.Shared.FrameworkLocationHelper' threw an exception.  C:\hostedtoolcache\windows\dotnet\sdk\9.0.200\Microsoft.Common.CurrentVersion.targets

Let's see if we can reproduce this inside a test in order to extract the inner exception and get the actual failure reason.

* Ensure that all Microsoft.Build.* package have the same version

Those are the direct dependencies of the Microsoft.CodeAnalysis.Workspaces.MSBuild package.

https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.MSBuild#dependencies-body-tab

* Improve diagnose

* Tweak how MSBuildLocator.RegisterDefaults() is called

Using a ModuleInitializer in Incrementalist.Cmd leads to race conditions when running the tests.

* Remove DiagnoseAzurePipelineFailure

It's now working properly!

---------

Co-authored-by: Aaron Stannard <aaron@petabridge.com>